FROM python:3.13-alpine

RUN addgroup -S startup && adduser -S -G startup -u 10001 startup

WORKDIR /app
COPY bus_revoketest_run.py /app/bus_revoketest_run.py

USER 10001:10001

CMD ["python", "/app/bus_revoketest_run.py"]
